### PR TITLE
test(routes): PUT /session/account 409 error message

### LINKED ISSUE #97: PUT /session/account 409 error message
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

When signing up with`PUT /session/account` and sending a `username` in the request body as defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/session/sign-up), there is a possibility that the username is already taken. If that happens, the server should return `409 Conflict` error. That already happens, but the error message is `Document update conflict` (which is the default message coming from CouchDB, which we use as database). 

### :dart: The goal

If a username is taken, the server should respond with `409 Conflict` and the message `An account with that username already exists`.

### :clipboard: Step by Step

- [x] claim this issue (@roubaeli)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Update the assertion in [tests/integration/routes/account/put-account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/tests/tests/integration/routes/account/put-account-test.js#L92) to test for the desired error message
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PUT /session/account 409 error message`
- [x] Start a Pull Request: #112
- [ ] Implement :) 
- [ ] Make sure tests pass. Commit with `fix: PUT /session/account 409 error message`
- [ ] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by roubaeli**
This is my first PR so can somebody assure me that I'm doing it correctly?
I've adjusted the tests to fail with the old error message.

--- 

closes #97

### CODE REVIEW

File: tests/integration/routes/account/put-account-test.js [hunk 1]
```diff
@@ -81,7 +81,7 @@ getServer(function (error, server) {
         .reply(201, [{
           id: 'org.couchdb.user:pat-doe',
           error: 'conflict',
-          reason: 'Document update conflict'
+          reason: 'An account with that username already exists'
```
Comment (gr2m) [inline tests/integration/routes/account/put-account-test.js]: You don’t need to change this part. Here we simulate what CouchDD would return when the document already exists, and CouchDB returns "Document update conflict". See this for comparison: https://wiki.apache.org/couchdb/HTTP_Document_API#line-233

File: tests/integration/routes/account/put-account-test.js [hunk 2]
```diff
@@ -90,7 +90,7 @@ getServer(function (error, server) {
         t.is(response.statusCode, 409, 'returns 409 status')
         t.is(response.result.errors.length, 1, 'returns one error')
         t.is(response.result.errors[0].title, 'Conflict', 'returns "Conflict" error')
-        t.is(response.result.errors[0].detail, 'Document update conflict', 'returns "Document update conflict." error message')
+        t.is(response.result.errors[0].detail, 'An account with that username already exists', 'returns "An account with that username already exists." error message')
```
Comment (gr2m) [inline tests/integration/routes/account/put-account-test.js]: perfect :ok_hand:

File: tests/integration/routes/account/put-account-test.js (hunk 1 above)
Comment (roubaeli) [inline tests/integration/routes/account/put-account-test.js]: Ok, thanks. Should I change it back? Also could you look at my fix? Thank you for helping me with this.

Comment (gr2m) [inline tests/integration/routes/account/put-account-test.js]: Yes, please change it back. I’ll comment on your fix in a minute

File: routes/utils/errors.js [hunk 3]
```diff
@@ -47,5 +47,9 @@ function parse (error) {
     error.message = 'Only admins can access /users'
   }
 
+  if (error.message === 'Document update conflict') {
+    error.message = 'An account with that username already exists'
+  }
+
```
Comment (gr2m) [inline routes/utils/errors.js]: Clever! That resolves the issue. But it has a potential side effect: besides user accounts we will also store other documents in the database in future. And as this code is run for all errors, it might change a conflict error for request documents to "an account with that username already exists" which would be confusing.

Instead of fixing it this way, I would suggest we handle this directly in the `accounts.add` method here: https://github.com/hoodiehq/hoodie-server-account/blob/8760b78cb2b0ec3802b05c42c946b642e25f0731/api/accounts/add.js

For comparison, see how we return a custom error if the password is incorrect in `session.add`: https://github.com/hoodiehq/hoodie-server-account/blob/8760b78cb2b0ec3802b05c42c946b642e25f0731/api/sessions/add.js#L25

I’m sorry to make it this complicated :/ if you like, we can merge you fix first, and make a follow up issue for this?

Comment (roubaeli) [inline routes/utils/errors.js]: No, it's ok. Thank you so much for your feedback! I will look into it and try to solve it in `accounts.add` method. But it can take me longer (few days) since I'm abroad and don't have access to my own computer. Is that a problem? I hope not cause I ould really like to finish this and then hopefully contribute some more.

Comment (gr2m) [inline routes/utils/errors.js]: no Problem Eliška, we are looking forward to your update :) Ping us if you have any questions

**Comment by roubaeli** [comment]
So I was trying to figure out how to catch the error. I've never used Promises before so I probably don't understand them correctly. If I try to add new `.then` function I seem to never get the error message at all. My first thought was to `.catch` the error and than throw back the correct one but tests then complain about not handling the error. Is this entirely incorrect aproach? Could you please send me to the right direction?

**Comment by seanjohnite** [comment]
I think that the .catch() callback function takes an error, as in https://github.com/hoodiehq/hoodie-server-account/blob/8760b78cb2b0ec3802b05c42c946b642e25f0731/api/accounts/update.js#L22. Does that help?

**Comment by roubaeli** [comment]
Yes, that is exactly what I was trying to do but when I run the tests they don't pass the first js standard part and fail with `error was expected to be handled`. I must have made some mistake but cannot find it.

**Comment by seanjohnite** [comment]
I could take a look if you want to push up that WIP commit.

**Comment by roubaeli** [comment]
Thank you for your help. Hopefully I finally figured out the problem. Of course I was totally overthinking it. All tests passed with this fix. Looking forwad to your comments.

File: api/accounts/add.js [hunk 4]
```diff
@@ -26,6 +27,13 @@ function addAccount (state, properties, options) {
 
   return state.db.put(doc)
 
+  .catch(function (error) {
```
Comment (seanjohnite) [inline api/accounts/add.js]: I might stick this `.catch` after the `.then`, but I believe they are functionally equivalent? Might just be a code style thing. @gr2m?

**Comment by seanjohnite** [comment]
Looks good! You'll probably want to rebase onto master. This is a pretty good article about that if you're interested: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by gr2m** [comment]
LGTM, thanks @roubaeli! Just needs cleanup of the commit messages. But we can help with that if you like? It should work something like this:

```bash
# rebase on top of latest `master` branch of the main repo
git remote add upstream git@github.com:hoodiehq/hoodie-server-account.git
git fetch upstream
git rebase upstream/master
# clean up your commits
git rebase -i head~4
```

The last command should open your editor and the first 4 lines should look something like this:

```
pick 179c9bb test(routes): PUT /session/account 409 error message
pick 5c721bb fix: PUT /session/account 409 error message
pick 43155df test(routes): PUT /session/account 409 error message
pick 879a9f1 fix: PUT /session/account 409 error message
```

change it to 

```
pick 179c9bb test(routes): PUT /session/account 409 error message
fixup 43155df test(routes): PUT /session/account 409 error message
pick 5c721bb fix: PUT /session/account 409 error message
fixup 879a9f1 fix: PUT /session/account 409 error message
```

then update your pull request with 

```
git push --force origin master
```

Let us know if you have any questions. I know this is all quite overwhelming, nobody really gets `git` :)

**Comment by roubaeli** [comment]
Cool! Thank you so much for that, it was actually really easy to do with those instructions. So is it ok now?

**Comment by finnp** [comment]
Awesome first PR! :tada:  LGTM

File: api/accounts/add.js (hunk 4 above)
Comment (gr2m) [inline api/accounts/add.js]: I agree with Sean, but also it’s no big deal :) I’ll merge it in
