### PR TITLE
401 responses for /session/account #81

### LINKED ISSUE #81: GET, PATCH, DELETE /session/account sould respond with 401 Invalid session, not 404 Not found
### The problem

When sending a `GET /session/account` request with an invalid session, the server responds with 404, as this is what [`session.find`](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/routes/account.js#L82-L84) returns.

### What we want

The correct way is to catch the `404` error and replace it with a `401` as we do it in [`GET /session/account/profile`](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/routes/profile.js#L44-L51)

### Steps to fix

**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) 

---

- [x] claim this issue (@matt-major)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Start a PR: #84
- [x] Adjust the test in [tests/integration/routes/account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/tests/integration/routes/account-test.js#L152-L164) to expect a `401 Invalid session` response, instead of the `404 Not Found` response
- [x] add a new test group within `PATCH /session/account` in the same file for `Session does not exist` and test for `401 Invalid session` response, move the current content into another group `Session does exist`. 
- [x] adjust the [DELETE /session/account without valid session test](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/tests/integration/routes/account-test.js#L318-L330) accordingly
- [x] make sure tests fail. Commit with `test(routes): /session/account 401 responses`
- [x] fix the behavior in [routes/account.js](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/routes/account.js)
- [x] Make sure all tests pass. Commit with `fix(routes): /session/account 401 responses`
- [ ] Someone else: review & merge

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by matt-major**
Fixes #81.

### CODE REVIEW

File: tests/integration/routes/account-test.js [hunk 1]
```diff
@@ -156,9 +156,9 @@ getServer(function (error, server) {
       server.inject(getAccountRouteOptions, function (response) {
         t.is(couch.pendingMocks()[0], undefined, 'all mocks satisfied')
 
-        t.is(response.statusCode, 404, 'returns 404 status')
+        t.is(response.statusCode, 401, 'returns 401 status')
         t.is(response.result.errors.length, 1, 'returns one error')
-        t.is(response.result.errors[0].title, 'Not Found', 'returns "Not Found" error')
+        t.is(response.result.errors[0].title, 'Unauthorized', 'returns "Unauthorized" error')
```
Comment (gr2m) [inline tests/integration/routes/account-test.js]: This should be `'Invalid session'` instead of `'Unauthorized'`

File: tests/integration/routes/account-test.js [hunk 2]
```diff
@@ -247,6 +247,20 @@ getServer(function (error, server) {
...
 
+    group.test('without valid session', function (t) {
+      var couch = couchdbGetUserMock
+        .reply(404, {error: 'Not Found'})
+
+      server.inject(patchAccountRouteOptionsPassword, function (response) {
+        t.is(couch.pendingMocks()[0], undefined, 'all mocks satisfied')
+        t.is(response.statusCode, 401, 'returns 401 status')
+        t.is(response.result.errors.length, 1, 'returns one error')
+        t.is(response.result.errors[0].title, 'Unauthorized', 'returns "Unauthorized" error')
```
Comment (gr2m) [inline tests/integration/routes/account-test.js]: `.title` should be `'Invalid session'` instead of `'Unauthorized'`

File: tests/integration/routes/account-test.js (hunk 1 above)
Comment (gr2m) [inline tests/integration/routes/account-test.js]: no, sorry :) `.title` is correct, but can you please add a check for `.detail`? `.detail` should be `'Invalid session'`

File: tests/integration/routes/account-test.js [hunk 3]
```diff
@@ -321,9 +335,9 @@ getServer(function (error, server) {
 
       server.inject(deleteAccountRouteOptions, function (response) {
         t.is(couch.pendingMocks()[0], undefined, 'all mocks satisfied')
-        t.is(response.statusCode, 404, 'returns 404 status')
+        t.is(response.statusCode, 401, 'returns 401 status')
         t.is(response.result.errors.length, 1, 'returns one error')
-        t.is(response.result.errors[0].title, 'Not Found', 'returns "Not Found" error')
+        t.is(response.result.errors[0].title, 'Unauthorized', 'returns "Unauthorized" error')
```
Comment (gr2m) [inline tests/integration/routes/account-test.js]: Can you please add a check for `.detail`? `.detail` should be `'Invalid session'`

**Comment by gr2m** [comment]
Thanks a lot for the great PR @matt-major, and welcome to Hoodie :)

I’ve left only 3 minor comments, could you incorporate these? Once done, this is good to merge :+1: 
If you can, could you squash the commits so there is only one `test...` and one `fix...` commit? Let me know if you need help with that, or I can also do it for you, if you prefer.

**Comment by matt-major** [comment]
@gr2m, no problem.

Additional tests added as requested, however the value returned by `errors.INVALID_SESSION` is `Session invalid` rather than `Invalid session`. The tests have been added to reflect this.

I have squashed the commits in to one for test & one for fix.
